name: Vulnerabilities-Audit

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    - uses: azure/container-scan@v0
      with:
        image-name: ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest
