name: VulnerabilitiesAudit

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_success:
    workflow: ["CI"]
#  workflow_run:
#    workflows: ["CI"]
#    branches: [main]
#    types:
#      - completed

jobs:
  aduit:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/container-scan@v0
      with:
        image-name: ${{ secrets.DOCKERHUB_USERNAME }}/web-app:latest
